### ISSUE TITLE
list-migrations clears migrations atom, causing migrate to not find any migrations

### ISSUE THREAD

**Issue by harob** [budu/lobos#51] opened 2012-11-20 03:23 UTC
The `lobos.core/migrate` function has been failing to run any of my migrations defined in my lobos/migrations.clj file. Looking at the lobos source and playing around in the REPL, it turns out that this is because `migrate` calls `lobos.migration/list-migrations`, which clears out the migrations atom and then reloads the migrations-namespace. That reload is not working for me; here is a REPL session to illustrate this:

```
$ lein repl
beancounter.core=> (require 'lobos.config 'lobos.core 'lobos.connectivity 'lobos.migrations 'lobos.migration)
nil
beancounter.core=> @lobos.migration/migrations
[#<migrations$reify__4373 lobos.migrations$reify__4373@5449ff3f>]
beancounter.core=> (lobos.migration/list-migrations)
[]
beancounter.core=> @lobos.migration/migrations
[]
```

And more specifically:

```
$ lein repl
beancounter.core=> (require 'lobos.config 'lobos.core 'lobos.connectivity 'lobos.migrations 'lobos.migration)
nil
beancounter.core=> @lobos.migration/migrations
[#<migrations$reify__4373 lobos.migrations$reify__4373@2d8b62e0>]
beancounter.core=> (swap! lobos.migration/migrations (constantly []))
[]
beancounter.core=> (use 'lobos.migrations :reload)
nil
beancounter.core=> @lobos.migration/migrations
[]
```

I don't know the rationale for the `use :reload` call; I assume it must usually successfully re-populate the migrations atom, but it does not seem to be doing so for me. This is on Clojure 1.4.0 and Leiningen 2.0.0-preview10.

Any ideas?

**Comment by budu** [comment] 2012-11-21 00:23
Yeah, I've seen reports about that bug, although I've never been able to reproduce it. I wonder if using reload to is not a dead end, but can't think of anything else right now.

**Comment by harob** [comment] 2012-11-21 01:06
Could you explain what the rationale for clearing the migrations atom and `use :reloading` 'ing the namespace is? If there is no strong one then we could just remove it. If it is just to avoid having to reload long-running REPL sessions, we could allow a work-around to the issue by having a `*reload-migrations*` var that can be set to true in the REPL, and causes the reloading to not happen when false. That obviously does not fix the underlying problem, but would allow the migration functionality to work in scripts or lein-lobos.

What do you think?

**Comment by budu** [comment] 2012-11-21 01:20
This looks like a good idea, `*reload-migrations*` default to true and lein-lobos modified to set it to false. I won't have time to test this for a while tough, pull requests are welcome!

**Comment by harob** [comment] 2012-11-21 03:25
I have submitted the pull request at https://github.com/budu/lobos/pull/52

**Comment by philc** [comment] 2012-11-29 23:47
I'm hitting this too. Any chance this could get merged and pushed to clojars?

**Comment by harob** [comment] 2012-12-04 20:13
Hi Budu, could you give an update on this? I am happy to help and personally need this, so let me know if there is anything blocking you from just merging and pushing in this pull request.

**Comment by budu** [comment] 2012-12-04 20:14
Don't seems to be any problem, I was just busy those past weeks, I'll check it out this evening.

**Comment by budu** [comment] 2012-12-05 02:09
I've merged your changes and took time to update the project.clj file to use lein2 and made 1.4 the default Clojure version. I also changed the version to 1.0.0-beta1 as Lobos has been quite stable for a while. I hope to find time this winter to close all remaining issues and finish the doc to release 1.0, it's been way too long!

Thanks again for your help.

**Closed as completed by budu** 2012-12-05 02:09 UTC

**Comment by harob** [comment] 2012-12-05 02:35
Great, thanks @budu!
